# Generated by Django 2.0.1 on 2018-04-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confighome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mappe', verbose_name='immagine')),
                ('order', models.IntegerField(default=0, verbose_name='posizione')),
                ('view', models.BooleanField(default=False, verbose_name='mostra')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creata il')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Mod. il')),
            ],
            options={
                'verbose_name': 'configurazione homepage',
                'verbose_name_plural': 'configurazione homepage',
                'db_table': 'pois_confighome',
            },
        ),
        migrations.AddField(
            model_name='poi',
            name='created',
            field=models.DateField(blank=True, null=True, verbose_name='Creata il'),
        ),
        migrations.AddField(
            model_name='poi',
            name='typecard',
            field=models.IntegerField(choices=[(0, 'free'), (1, 'a pagamento'), (2, 'pubblica')], default=0, null=True, verbose_name='Tipo di scheda'),
        ),
        migrations.AddField(
            model_name='confighome',
            name='poi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pois.Poi'),
        ),
        migrations.AddField(
            model_name='confighome',
            name='poitype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pois.Poitype'),
        ),
    ]
