# Generated by Django 2.0.1 on 2018-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0002_auto_20180409_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='short',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Descriz. breve'),
        ),
        migrations.AddField(
            model_name='poitype',
            name='short',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Descriz. breve'),
        ),
        migrations.AlterField(
            model_name='confighome',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img_home', verbose_name='immagine'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Creata il'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='typecard',
            field=models.IntegerField(choices=[(0, 'free'), (1, 'a pagamento'), (2, 'pubblica')], default=0, null=True, verbose_name='Scheda'),
        ),
    ]
