# Generated by Django 2.0.1 on 2018-06-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0003_auto_20180508_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='imageA',
            field=models.ImageField(blank=True, null=True, upload_to='resources', verbose_name='Immagine A'),
        ),
        migrations.AddField(
            model_name='poi',
            name='imageB',
            field=models.ImageField(blank=True, null=True, upload_to='resources', verbose_name='Immagine B'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='typecard',
            field=models.IntegerField(choices=[(0, 'free'), (1, 'a pagamento'), (2, 'pubblica'), (3, 'promozione')], default=0, null=True, verbose_name='Scheda'),
        ),
    ]
